### PR TITLE
:pill: Fix a new line error

### PR DESCRIPTION
**Pull request by dhanvi**
Well I am seeing this weird error in my atom editor 

screenshot from 2015-05-06 18 28 27
which adds writeups to the top so I have to manually fix this every time hope that the new line fixes it :+1:

### CODE REVIEW

**Comment by dhanvi** [comment]
Also @mathiasbynens how about adding me to the admins :smile: Well I do know that with great power comes great responsibility :100:

**Comment by abpolym** [comment]
Thanks @dhanvi , I fixed it. Have to close this pull-request though, since genctf.py moved and caused a merge conflict with this PR.

**Comment by dhanvi** [comment]
On Mon, May 18, 2015 at 3:34 PM, polym notifications@github.com wrote:

> Thanks @dhanvi , I fixed it. Have to close this pull-request though, since genctf.py moved and caused a merge conflict with this PR.

No problem hope it's fixed now :)

**Comment by dhanvi** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLkxzSFdKTmswRWVXVURSSWRTemJyeHciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDY1Y2MxM2RhZTMwMDVjYjU4NTU5ZmU1MmE2ZWRmZWU5MjkxNDEwOWMxNjU5MTA5MmNmMDAwMDAwMDExMTcxN2IyNDkyYTE2OWNlMDQ2MzNiZGRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uTHNIV0pOazBFZVdVRFJJZFN6YnJ4dyJ9fSwidXNlcklkIjotMX0.q5zuVei8D1TSANsbwDtxyUJZdNdQQzSF8DKpxaHkcO4  
My Courses
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLkxzSFdKTmswRWVXVURSSWRTemJyeHciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDY1Y2MxM2RhZTMwMDVjYjU4NTU5ZmU1MmE2ZWRmZWU5MjkxNDEwOWMxNjU5MTA5MmNmMDAwMDAwMDExMTcxN2IyNDkyYTE2OWNlMDQ2MzNiZGRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uTHNIV0pOazBFZVdVRFJJZFN6YnJ4dyJ9fSwidXNlcklkIjotMX0.q5zuVei8D1TSANsbwDtxyUJZdNdQQzSF8DKpxaHkcO4 
Course Catalog
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5Mc0hXSk5rMEVlV1VEUklkU3picnh3IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA2NWNjMTNkYWUzMDA1Y2I1ODU1OWZlNTJhNmVkZmVlOTI5MTQxMDljMTY1OTEwOTJjZjAwMDAwMDAxMTE3MTdiMjQ5MmExNjljZTA0NjMzYmRkQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLkxzSFdKTmswRWVXVURSSWRTemJyeHcifX0sInVzZXJJZCI6LTF9.TUsWuqaJuLWGHgQ4F_0NZRS9jHCD6te5K_YCdqqoEh0

Tummala Dhanvi thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49NWY2NTRiYjdjNWE5ZWVhZWU3YzVkMjQ1MjcxYTIzZDgmZW1haWw9cmVwbHkrMDA2NWNjMTNkYWUzMDA1Y2I1ODU1OWZlNTJhNmVkZmVlOTI5MTQxMDljMTY1OTEwOTJjZjAwMDAwMDAxMTE3MTdiMjQ5MmExNjljZTA0NjMzYmRkQHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1jdGZzL3dyaXRlLXVwcy10b29scz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5Mc0hXSk5rMEVlV1VEUklkU3picnh3IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA2NWNjMTNkYWUzMDA1Y2I1ODU1OWZlNTJhNmVkZmVlOTI5MTQxMDljMTY1OTEwOTJjZjAwMDAwMDAxMTE3MTdiMjQ5MmExNjljZTA0NjMzYmRkQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLkxzSFdKTmswRWVXVURSSWRTemJyeHcifX0sInVzZXJJZCI6LTF9.eHrgIys_QErxNHBgbIO3Np1vqWV02OY5rjLkY-jg1Ak
Download our App:  iOS
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5Mc0hXSk5rMEVlV1VEUklkU3picnh3JnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDY1Y2MxM2RhZTMwMDVjYjU4NTU5ZmU1MmE2ZWRmZWU5MjkxNDEwOWMxNjU5MTA5MmNmMDAwMDAwMDExMTcxN2IyNDkyYTE2OWNlMDQ2MzNiZGRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uTHNIV0pOazBFZVdVRFJJZFN6YnJ4dyJ9fSwidXNlcklkIjotMX0.q4btBZvi3WRaKkwXe-p6Eg9xZsx2-dXZhpdVbn-D6bE 
  |  Android
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uTHNIV0pOazBFZVdVRFJJZFN6YnJ4dyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNjVjYzEzZGFlMzAwNWNiNTg1NTlmZTUyYTZlZGZlZTkyOTE0MTA5YzE2NTkxMDkyY2YwMDAwMDAwMTExNzE3YjI0OTJhMTY5Y2UwNDYzM2JkZEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5Mc0hXSk5rMEVlV1VEUklkU3picnh3In19LCJ1c2VySWQiOi0xfQ.8ZWIW18kvI0FjuxbrVaVyWWPofgcw3nWRJ_8bjPDDWo
Learner Help Center
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uTHNIV0pOazBFZVdVRFJJZFN6YnJ4dyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNjVjYzEzZGFlMzAwNWNiNTg1NTlmZTUyYTZlZGZlZTkyOTE0MTA5YzE2NTkxMDkyY2YwMDAwMDAwMTExNzE3YjI0OTJhMTY5Y2UwNDYzM2JkZEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5Mc0hXSk5rMEVlV1VEUklkU3picnh3In19LCJ1c2VySWQiOi0xfQ.reJc70COYfjIguA2h9P-2jQjrXzj76uL1b5qA4Zkqkk 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS9SYlRJNjNSb2o2U1lLYy1rYktCS3p4SWYwdDMwZ2xkamY0OXpxSlUxMWVoY01ReFJGUEVjU29XZmtra0dLUTN4UlM5NWxIc21IdlZGQTQxMWVzSXRzZy5abFh2dENpSHhHQWJaYmRBNzJ0V05BLk9KQ01EOXBObndVdnNwMEpuZVdjSzJvVHc5aDRqT0dZM0dBdi1SSjNIcTZiZm1hVUE1OXF3R0s5THpsaG15Z19CV19xQ2JrM0prOGt2RUMyXzU4eG12MjRPa0thYjJFSFBTem1LSjVieUNNU3pCekNVV0JFWm51dVBHWFVOTDNENUVHRFZJeWw5b19FVXZhUXFOQjZMMXFEY1VXdmt3Q1F5cURyXzJFc3JKU2pGZWxPRXdueVpublowVUhiMGRyckx5VjY2R3I1OGZGQ18yaTRrOVRtVDNQVHR1UTdRbXp3MlRRT0I3b2lrR0s1Ymtqc2NWMFl0T1BnM215Sl85cFFVZkxaa3dRbW42TklMVk4yN0M1LWxjcHMtN2duU3lGS1NJdWdGcHBjdEt3P3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLkxzSFdKTmswRWVXVURSSWRTemJyeHciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDY1Y2MxM2RhZTMwMDVjYjU4NTU5ZmU1MmE2ZWRmZWU5MjkxNDEwOWMxNjU5MTA5MmNmMDAwMDAwMDExMTcxN2IyNDkyYTE2OWNlMDQ2MzNiZGRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uTHNIV0pOazBFZVdVRFJJZFN6YnJ4dyJ9fSwidXNlcklkIjotMX0.ALAXgzO0DY2inMK5oEF8l6YCXqWydZaMnT4H7Oa7jxQ
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA

**Pull request closed without merging**
